### ISSUE TITLE
Windows don't cover the panel

### ISSUE THREAD

**Issue by tjammer** [peterfajdiga/karousel#15]
I have a panel set up as `Windows Can Cover`, but tiled windows with karousel don't cover the panel. Instead they are below.

I'm on Plasma 5.27.6 on X11

**Comment by peterfajdiga** [comment]
Thanks for the report, I haven't thought about this case. The problem is that I set _Keep Below Others_ for all tiled windows, so that floating windows are always above them. I'm not sure how to solve this. I suppose I could add a setting that disables this behavior.

**Comment by tjammer** [comment]
What about using _keepAbove_ for floating windows and leaving tiling windows in their default state? Could that work?
I don't know how that might interact with other windows (popups etc).

**Comment by peterfajdiga** [comment]
That's a good suggestion. This would work, but then floating windows will cover panels that are set up as _Windows Go Below_. And you would lose the ability to set some floating windows as above other floating windows.

In other words, instead of these three layers:
- Tiled (keep below others)
- Floating (normal)
- Floating (keep above others)

you would have these:
- Floating (keep below others)
- Tiled (normal)
- Floating (keep above others)

I'm not sure if you'd ever want to set floating windows behind tiled, because that would make them almost always obscured, so you might as well minimize them.

That's why I wouldn't make this solution the default. But it would work well for your case, as long as you don't use _Keep Below Others_ for floating windows, so it might make sense to add an option for this.

**Comment by tjammer** [comment]
I agree. As there is no _one size fits all_ solution here, an option seems the way to go here.
Thanks for the quick response!

**Comment by Maxinova** [comment]
Hey! I was just about to create an issue for that. Another possibility I can suggest is adding a "Window Rules" option to specify which apps should not have the "Keep Below Others" attribute.

**Comment by peterfajdiga** [comment]
Hi, thanks for the suggestion, but won't that make some windows (those that don't have the window rule set) still appear behind the panel?

**Comment by Maxinova** [comment]
Yes, indeed. I didn't provide all the information. The "Always keep below" feature is problematic for me as it only affects Steam games running through Proton in fullscreen mode. When I launch such a game, it goes fullscreen, but with the panel on top of the game, and I have to manually adjust the "Keep above windows" setting to make it truly fullscreen. Disabling Karousel resolves the problem. That's why I suggested a Window Rule – with that, it would be possible to manually add games to avoid encountering this issue.

**Comment by peterfajdiga** [comment]
I added the keepAbove setting (the first solution). @Maxinova does this also work for your use case?

**Comment by Maxinova** [comment]
It is working perfectly well now. Thank you very much !
