### ISSUE TITLE
Maximized windows are resized on focus switch

### ISSUE THREAD

**Issue by tjammer** [peterfajdiga/karousel#18]
Maximized (and fullscreen) programs are resized when I switch focus to the next column. If I switch focus back to the previously maximized window, it keeps its smaller size.
Curiously, I have this problem only on one machine. On my other machine the windows are resized back to maximized (or fullscreen) when I switch focus back to them.

Do you have any ideas what could cause this? I tried wiping most KDE settings, in particular kwinrc.

The system where the problem occurs has the following versions:
Plasma: 5.27.6
KDE Frameworks: 5.108.0
Qt: 5.15.9
Graphics Platform: X11 (but also happens on Wayland)

**Comment by peterfajdiga** [comment]
Hi, un-maximizing and un-full-screening windows when switching focus to another tiled window on the same desktop is intentional, to make space on the screen for other tiled windows. Re-maximizing them was also intentional, but I've recently removed this feature (in 0.4) because it was a bit of a pain to maintain and I was not sure about its usefulness. Sorry for not documenting this change and thank you for letting me know that it is indeed useful. I'll consider re-implementing this (hopefully in a better way) for the next version.

**Comment by tjammer** [comment]
Good to know, then I can use the 0.31 release for now.

I agree that un-maximizing on focus switch is super useful btw. My main workflow has a fullscreen editor in the center with terminals left and right. Being able to see a scaled down version of the editor when one on the terminals is in focus is an upgrade to just seeing a few line endings.

Looking forward to the next release
