### ISSUE TITLE
Local Development & Toggle Stacked Layout

### ISSUE THREAD

**Issue by r0skar** [peterfajdiga/karousel#20]
Hei! First of all, thanks for your work on this - it works great! I have a couple of random questions.

I am a web developer and never checked out other platforms. Now, I'd like to add a couple of things to this script, but wonder what the usual local development process looks like for you? eg. does one really have to manually disable/enable to script after every change? How does debugging/logging work? I tried adding a `print` statement and watched the output of `journalctl -g "js:" -f`, however nothing is being printed.

And one more thing: about the Meta-X shortcut to toggle stacked layouts: its not really doing anything for me. I was expecting following behavior:

- Press Meta-X
- Open a new window
- The window gets placed below the current one instead of next to it.

However, at the moment nothing really happens after I press Meta-X. The only way to get windows to stack vertically is if i move them to the left/right after creating them. And when moving a window, it seems that they always get put below their sibling before advancing a column. Is this behavior a feature or a bug? :)

**Comment by peterfajdiga** [comment]
Hi, thanks for your interest!

What I do after every change is `make install && killall kwin_x11`. :slightly_smiling_face:
For logging I use this function: https://github.com/peterfajdiga/karousel/blob/a5ecc94479bdea3bf963648935338e1620ffbd39/src/utils/log.ts#L1
However, there is no "js:" prefix in the logs, instead there's a "qml:" prefix, because this script is a `declarativescript`.

As for the Meta+X shortcut, it just toggles between normal column mode (all windows in the column are visible) and stacked mode (one window in the column is visible, others are shaded). Kwin on Wayland doesn't seem to support shaded windows, so this doesn't do anything there. I really need to update the readme and the tooltips in the config dialog. Thanks for pointing this out!

Regarding the last question, that is the intended behavior. If you want to only advance a column, use Meta+Ctrl+Shift+A/D.

**Comment by r0skar** [comment]
Thanks Peter - I forgot to mention that I am indeed on Wayland, so that all makes sense. As for killing kwin - I think thats not [yet](http://blog.davidedmundson.co.uk/blog/qt6_wayland_robustness/) implemented with wayland (afaik it will kill all apps when the compositor is restarted).

Still not a 100% sure about the logging - I tried putting a `log` in the init script and ran `journalctl -g "qml:" -f` and then restarted Karousel. Nothing showed up. Did I miss something obvious? :thinking: 

 I will look into adding new behavior to the Meta-X thing to match the expectation I initially had in a local branch and see how far I get.

**Comment by peterfajdiga** [comment]
Perhaps you're facing the same issue I have when I do the following:
1. disable Karousel
2. make changes to the code
3. run `make install` to install the changed version
4. re-enable Karousel

If I do these steps, I'd expect the new version to be loaded, but it actually loads the old one. To get the new version running, I actually have to restart kwin.

**Comment by r0skar** [comment]
> If I do these steps, I'd expect the new version to be loaded, but it actually loads the old one. To get the new version running, I actually have to restart kwin.

Yep that was it :+1: Can see the logs as expected. Its gonna be cumbersome to do in Wayland (AFAIK it means I have to log out and login again to see changes), but hopefully that gets fixed soon. Thanks again for all your help!
