### ISSUE TITLE
Overview doesn't show all applications

### ISSUE THREAD

**Issue by ashkitten** [peterfajdiga/karousel#32]
When I use the overview, only applications currently visible (scrolled onto screen) appear. I would expect that all windows appear in overview.

**Comment by peterfajdiga** [comment]
Hi, it seems that Overview doesn't include windows that are off-screen. I don't see what could be done in Karousel about it, unfortunately.

**Comment by ashkitten** [comment]
is an event raised when opening the overview? perhaps a workaround could be to move all windows on-screen only during overview presentation

**Comment by peterfajdiga** [comment]
There doesn't seem to be a signal for effects.

**Comment by gleyconJ** [comment]
I have a suggestion for you. Because it bothers me a lot not being able to see all the windows in the "Overview". However, if I minimize all windows and then go to "Overview", all windows are there. But I need to do this in two steps: minimize everything and then overview. If you managed to create a screen corner feature and a plasmoid button to include the two steps in one, it would work almost identically to the original.

**Comment by baduhai** [comment]
I do believe this has been fixed. At least I no longer have this problem, since upgrading to Plasma 6.

**Comment by gleyconJ** [comment]
Hello!
Yes. This problem no longer exists. After a specific Plasma 6 update, Karoussel became 100% functional in this part. Whether it was a coincidence or not I don't know. But this problem no longer exists.

**Comment by peterfajdiga** [comment]
Fixed in Plasma 6
