### ISSUE TITLE
Spectacle's popup "tooltip" while in Window Under Cursor mode is tiled and should probably be excluded.

### ISSUE THREAD

**Issue by puddles54** [peterfajdiga/karousel#46]
The window I'm referring to is the one that pops up when you press (by default) Meta+Ctrl+PrtSc. Sorry I can't take a screenshot of it because when you're in this mode Spectacle won't take a screenshot without selecting a window and you can't select this little popup window to screenshot. It's a little tooltip-like pop up in the center of your screen, however with karousel enabled it tiles it like a usual window.

I suspect it's as simple as adding an exclusion in the window rules tab in karosel's settings, but I have no clue how to get the properties of this window since I can't click on it without it disappearing.

**Comment by peterfajdiga** [comment]
Thanks a lot for the report! It turns out that the class and caption of this window are both empty strings. But I also noticed that the Kwin scripting API returns -1 as the pid of the window. I'll try excluding windows with pid = -1, but I need to test for a while first, to see if this also prevents tiling of any other window that should be tiled.
