### ISSUE TITLE
Feature Request: Toggle between scroll modes

### ISSUE THREAD

**Issue by Zetaphor** [peterfajdiga/karousel#48]
First of all, thank you for creating this. I've always wanted to use a TWM but they never really stuck. Now I can have the parts of that I liked while being able to stay on KDE.

It would be great if I could bind a keyboard shortcut to toggling between the different scrolling modes, (scroll as neccesary, center focused, center visible)

For my particular use case I want to use the center focused column most of the time, but then there are time I find myself wishing I could easily switch over to "only scroll as necessary" so that I can easily put two windows side by side in a 70/30 or 50/50 split.

Using KDE 6 on Wayland.

**Comment by peterfajdiga** [comment]
Hi, thanks for the suggestion. I'll think about it. In the meanwhile you could use "only scroll as necessary" and press the Meta+Alt+Return shortcut when you want a column centered. Though I understand that doing it this way could get tedious if you need it often.

**Comment by Zetaphor** [comment]
I hadn't even considered that, I think I can actually handle this using the key macro feature of my keyboard (UHK v2) which I use for most things anyway. Thanks for the suggestion!

What is the technical limitation requiring a restart of the script after changing settings? I'm only just starting to learn my way around KWin scripting.

**Comment by peterfajdiga** [comment]
@Zetaphor The reason a restart is required is that the KWin Scripting API unfortunately doesn't include a signal to notify the script that its config has been changed. A work-around could be a keyboard shortcut for re-loading the config, but I think it's not required, since you most likely already have the KWin Scripts System Settings module open when changing a script's config, so you can restart it from there.

**Comment by peterfajdiga** [comment]
Not planned for now.
