### ISSUE TITLE
[Bug] Super + arrow keys don't seem to work

### ISSUE THREAD

**Issue by johnwoltman** [peterfajdiga/karousel#59]
Karousel version: 0.9.4
Plasma version: 6.1.4
X11 / Wayland: X11

Description: I have tried assigning arrow keys, such as Super + Left to  focus left, Super + Right to focus right, and Shift+Super+Left to move left, but they do not seem to work.  I removed the default KWin bindings, but still have had no luck.  Is there another setting, maybe in KWin or somewhere else in Plasma, that would prevent arrow keys from working in Karousel?

**Comment by peterfajdiga** [comment]
No, not that I know of. Does this only happen with arrow keys?

**Comment by ZenurikSD** [comment]
I use the Super + Arrows shortcut to move my windows between columns just fine. When changing them to "move focus" it didn't work immediately; I had to restart kwin with the `kwin --replace` command and remap the shortcuts again because the setting didn't seem to save, but now it works fine on Wayland.

**Comment by johnwoltman** [comment]
I am going to the kwin --replace thing.  I'd like to get it working so I'll also check with other keys.

**Comment by johnwoltman** [comment]
The kwin --replace worked - I have successfully assigned Super+arrows to focus, and shift+super+arrows to move.  Thank you
