### ISSUE TITLE
[Feature request] Allow centering of all columns in 'Only scroll as necessary'

### ISSUE THREAD

**Issue by humanplayer2** [peterfajdiga/karousel#66]
In _Only scroll as necessary_ scrolling mode, it is not possible to center on columns if there are not wide enough columns on its sides, cf. discussion in #35. 

It would be nice if it was possible to center on arbitrary columns.

**Comment by humanplayer2** [comment]
Thank you, yes, but it scrolls more than necessary for me.

E.g. say I have three windows `A`, `B`, `C` that take up respectively 30%, 20%, 30% of my ultrawide monitor. 
 - I work in `C`, and want that centered. 
 - When `C` is centered, `A` is moved beyond the left edge of the screen: that's OK, I only need it later. 
 - I have information in `B` that I copy into `C`. `A` I only need later. .

I can move focus to `C` and center it. That's nice. However, when I move focus to `B`, `B` is centered, which I don't want. When I move back to `C`, I have to re-center it.

**Comment by xegx** [comment]
I would also appreciate this feature.

Then the shortcut to center the focused window (Meta+Alt+Return by default) would have a consistent outcome in the scroll as necessary mode: center the focused window no matter what, even if some 'blank' desktop was shown to the right or left. 

That might be the case if the focused window was in the start or end column, but also if the focused window was close enough to the start or end column that centering it would also reveal some of the 'blank' desktop to the left or right of the screen.

Your kwin script is very useful on wide monitors. Thank you for your work.

**Comment by peterfajdiga** [comment]
I misunderstood the original comment in this issue. So if I understand correctly now, this is the same as https://github.com/peterfajdiga/karousel/issues/35 ?

If yes, this has already been fixed in commit https://github.com/peterfajdiga/karousel/commit/fb1047c8ba9a4699f20cac755e1ef0d18ee3350e, but I haven't created a release with the fix yet.

**Comment by xegx** [comment]
I've just tried revision [c60cfeb](https://github.com/peterfajdiga/karousel/commit/c60cfeb521be9d039e4fcd405c7f2639370a80fa) and the "Center focused window (Scrolls so that the focused window is centered in the screen)" command now operates as I'd prefer (as described  in my previous comment) when using the "Scroll as necessary" mode.

I won't speak for the original feature requester but I find this Karousel behaviour more consistent and preferable. I also think it fulfills this feature request.

I think this current feature request is related to the last line of 
[#35](https://github.com/peterfajdiga/karousel/issues/35) where the feature requester asks for a second feature. So I don't think this #66 is exactly the same as #35 because two features were requested there.

Thanks very much.

**Comment by humanplayer2** [comment]
I agree with @xegx, both wrt consistency of behavior and wrt how this was supposed to relate to #35 . Thank you @peterfajdiga for implementing this!

**Comment by humanplayer2** [comment]
@peterfajdiga , the last 0.11 release broke this feature. With _Only scroll as necessary_, I can no-longer center on the outer-most windows.

**Comment by peterfajdiga** [comment]
@humanplayer2 Thanks for letting me know! Annoyingly, it still works for me, even on 0.11. Do you have the problem on X11 or Wayland or both?

**Comment by humanplayer2** [comment]
My apologies, a reboot solved it. Thank you very much for solving this, _Only scroll as necessary_ is really spot on for me now!
