### ISSUE TITLE
Feature request - "Real" Infinite Carousel

### ISSUE THREAD

**Issue by wesbluemarine** [peterfajdiga/karousel#7]
Would be possible to add an option to make Karousel a true infinite carousel? Scrolling back to the first window should bring the focus to the last one, scrolling forward to the last window should bring it back to the first.

**Comment by peterfajdiga** [comment]
It would be possible and I see two ways of doing this:
- as a true infinite carousel, as you put it, where windows also get re-positioned, so that it gives the illusion of endless circular movement
- without re-positioning windows, but only moving focus circularly, when using Meta+A and Meta+D

The former option would make it easier for the user to get lost in their windows as there would effectively be no first and last window. It would also make the Meta+[N] key bindings useless.

The latter option would be reasonable and easy to implement. You can already achieve jumping to start and end using the key bindings Meta+Home and Meta+End, though. Would it still be useful to do this with Meta+A and Meta+D as well?

**Comment by wesbluemarine** [comment]
I think the second option it's the best for both users and you (developers).
I found intuitive/useful to jump to start and end with Meta+A and Meta+D.
Thanks a lot for your work!

**Comment by peterfajdiga** [comment]
Hi again, I need some more convincing for this. I've been thinking about this a bit and I have some doubts, which I'll list here:
- I find that in most GUI elements in software (with the exception of menus), items don't wrap around, so I wouldn't say one way is more intuitive than the other.
- If you don't have animations enabled, it might be confusing for Meta+D to move from the last column to the first one, as it wouldn't be obvious where you landed or even that the direction changed.
- When Meta+D doesn't do anything, it gives feedback to the user that the last column has been reached. With wrap-around, this feedback would be lost.
- You can already jump to start and end with Meta+Home (or Meta+1) and Meta+End.
